### PR TITLE
Add GrapheneOS Google Play links

### PR DESCRIPTION
**Pull request by Flash1232**

### CODE REVIEW

**Comment by Psyhackological** [comment]
Hi
Thank you for your pull request! I was going to do that myself, so thanks!
I prefer default app names on your phone.
Example: `Secure Camera` on Google Play will be installed as `Camera`.
However I think that is a good exception, so merging.
I checked the links and they work fine.

**Comment by Psyhackological** [comment]
Hi
Thank you for your pull request! I was going to do that myself, so thanks!
I prefer default app names on your phone.
Example: `Secure Camera` on Google Play will be installed as `Camera`.
However I think that is a good exception so merging.
I checked the links and they work fine.

**Comment by Flash1232** [comment]
Thank you! :)

**Comment by thestinger** [comment]
Deleted my original comment and posting it again with a clearer explanation of our naming approach.

We use shorter names for the app labels in the OS because it looks much nicer. Google Camera also calls itself Camera for the English app label as another example. Long names don't work well with most launchers since they get cut off and partially replaced with `...`. We often refer to the app as the GrapheneOS Camera and GrapheneOS PDF Viewer in the context of talking to the GrapheneOS community, but we use Secure Camera and Secure PDF Viewer on the Play Store to get the purpose of the app across better. It probably makes sense to do the same here as was done by this pull request. On the Play Store, we don't need to say GrapheneOS in the app name because the Play Store prominently lists GrapheneOS as the developer of the app already. We can freely change the Play Store app name from Secure Camera to Private Camera, etc. to try out different approaches. You only get up to 30 characters for new app names on the Play Store now so we can't really stick much in there to help boost it in search.

The unambiguous name of an app is the app id such as app.grapheneos.camera and app.grapheneos.camera.play for the variants of our Camera app. Many apps have the same app labels and app labels vary based on language. Play Store listing app name can be freely changed without app updates, also varies based on language and can also be the same as other apps. Developer names can also be the same, although their numerical id and developer page would be different.

It's hard to say exactly what should be used to refer to apps. It's really just whatever describes them best if you aren't using the app id since app label / store name are ambiguous.

**Pull request merged**
