### PR TITLE
Fix icon links

### PR DESCRIPTION
**Pull request by KaranKad**
Current icon link gives 404 so here is the updated link.

### CODE REVIEW

**Comment by KaranKad** [comment]
I just noticed that there are other apps with same issue. I'll update all of them in one go.

**Comment by Psyhackological** [comment]
Ow god, I haven't checked PRs for a while. Sorry. You're right, you can continue fixing icons, or I can do it myself.

**Comment by KaranKad** [comment]
Allright, I've updated all icon links.

**Comment by Psyhackological** [comment]
# Thank you!

Squashing and merging...

**Pull request merged**
