### PR TITLE
Added new apps

### PR DESCRIPTION
**Pull request by metezd**
The 2FA app has an anti-feature but except that it is as good as them. (I am thinking to replace it with FreeOTP Plus)

I added adblocking category for the people who might want to find alternatives for their closed source adblocking apps.

### CODE REVIEW

**Comment by XXDRD** [comment]
> The 2FA app has an anti-feature but except that it is as good as them. (I am thinking to replace it with FreeOTP Plus)
> 
> I added adblocking category for the people who might want to find alternatives for their closed source adblocking apps.

What is the anti feature in Aegis

**Comment by Psyhackological** [comment]
I see. Will it work on the De-googled smartphone though?
> NonFreeDep: The application depends on a non-free application (e.g. Google Maps) - i.e. it requires it to be installed on the device, but does not include it.

 Last time I tried this app and it gave me wrong codes in some apps. Do you used each of these apps in ad-blocking category?

**Comment by Psyhackological** [comment]
@XXDRD I think he meant [Authenticator Pro](https://android.izzysoft.de/repo/apk/me.jmh.authenticatorpro)

**Comment by metezd** [comment]
> What is the anti feature in Aegis

I meant Authenticator Pro.

> Last time I tried this app and it gave me wrong codes in some apps.

I use the app for 3+ months. Works like a charm for me

> I see. Will it work on the de-googled smartphone though?

Not tested (My device isn't fully de-googled) My opinion is it should work for de-googled device because the non-free dependencies for Wear OS part of the app.

> Do you used each of these apps in ad-blocking category?

Yes, I used each app. At least for a day. The one I used for the longest time and was satisfied with was RethinkDNS. InviZible Pro is more configurable than the other apps.

**Comment by metezd** [comment]
> Why did you remove [this](https://github.com/blokadaorg/blokada)? Curiosity.

Confliction with the rules (It just has 2 anti-features which I don't think is a really big deal). I'm thinking of creating a second PR and adding it and a few more applications 🤔

**Comment by Psyhackological** [comment]
Do that. I'm going to create separate markdown file `PRIVACY.md` where I am going analyse deeply current apps. Example:
1. Anti-features and what does it mean in simple text
2. Exodus trackers (best is 0)
3. Link to privacy policy in source code repository.

**Comment by Psyhackological** [comment]
Yes, you're right, however I've always wanted to keep it clean. The list now has 1723 lines and I think the deep insight of those apps should be in separate file. If someone wants to know then he searches for his app.

**Comment by XXDRD** [comment]
> Yes, you're right, however I've always wanted to keep it clean. The list now has 1723 lines and I think the deep insight of those apps should be in separate file. If someone wants to know then he searches for his app.

We could just add a link to their heading in `PRIVACY.md` 
But I still think that a website would be best to display that sort of info

**Comment by Psyhackological** [comment]
That is a good idea too.
Yeah I know that, however I wasn't planning to do a website that is why is made an easy to edit MarkDown file. Maybe in the future, because I self-learn a lot and doing projects. This idea and project is currently put down for me.

**Pull request merged**
