### PR TITLE
Cloudstream does not currently have a website

### PR DESCRIPTION
**Pull request by dotziph**
This is a unofficial fan website. The Dev's have said in the discord multiple times that this is not theirs. This means at anytime the owner could change the link to something malicious.

### CODE REVIEW

**Comment by Psyhackological** [comment]
### Hi, thanks for Pull Request.
Could you give me some kind of proof like preferably source link or screenshot? Then I can merge it.

**Comment by XXDRD** [comment]
idk how to make edits in PR, so added a new PR where I added the cloudstream's offical webpage #62

**Comment by Psyhackological** [comment]
Sure, closing because of #62.

**Comment by dotziph** [comment]
> ### Hi, thanks for Pull Request.
> Could you give me some kind of proof like preferably source link or screenshot? Then I can merge it.
 Currently on my phone so it's kind of a bad screenshot but here it is.

**Comment by dotziph** [comment]
> idk how to make edits in PR, so added a new PR where I added the cloudstream's offical webpage #62 

This also isn't the official website, that's a prerelease and is in heavy development.

**Comment by Psyhackological** [comment]
I'm not gonna lie - I don't know what to do with it. Probably let it be for now. If something malicious happens I will know about this.

**Pull request closed without merging**
