### PR TITLE
Add Blade Player

### PR DESCRIPTION
**Pull request by DoYouNotice**
## Blade Player
- [x] Installed and tested by me on my main smartphone and used for about 15 minutes or more.
- [x] Has dark theme.
- [x] It has 0 trackers on [εxodus](https://reports.exodus-privacy.eu.org/en/reports/v.blade/latest/).
- [x] It has 1 F-Droid [Anti-Features](https://apt.izzysoft.de/fdroid/index/apk/v.blade).
- [x] I use the app on a daily basis and I love almost the entirety of it, so I placed next to it a heart.

### CODE REVIEW

**Review by XXDRD — COMMENTED** [review]
Did you really test this app?
I was unable to test this because of no Spotify app !
I wonder how Spotify would react to an app like this?

**Comment by DoYouNotice** [comment]
yea i daily drive this app works pretty well. Replaces for me the Spotify client.
It still has little bugs but nothing to big

**Review by XXDRD — APPROVED** [review]

**Comment by Psyhackological** [comment]
> yea i daily drive this app works pretty well. Replaces for me the Spotify client. It still has little bugs but nothing to big

Could you describe those `little bugs`, please?

**Comment by Psyhackological** [comment]
However you've already submitted PR with Burning Series so this is a duplication of PR.

**Comment by DoYouNotice** [comment]
> > yea i daily drive this app works pretty well. Replaces for me the Spotify client. It still has little bugs but nothing to big
> 
> Could you describe those `little bugs`, please?

you can look here there i described it
https://github.com/vhaudiquet/BladePlayer/issues/13#issue-1204817404

**Pull request closed without merging**
